Controllers/FaqsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using epeacweb.Contracts;
using epeacweb.Data;
using epeacweb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace epeacweb.Controllers
{
    public class FaqsController : Controller
    {
        private readonly IFaqRepository _repo;
        private readonly IMapper _mapper;

        public FaqsController(IFaqRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }
        // GET: Faqs
        public ActionResult Index()
        {
            var faqs = _repo.FindAll().ToList();
            var model = _mapper.Map<List<Faq>, List<FaqViewModel>>(faqs);
            return View(model);
        }

        // GET: Faqs/Details/5
        public ActionResult Details(int id)
        {
            if(!_repo.isExists(id))
            {
                return NotFound();
            }
            var faq = _repo.FindById(id);
            var model = _mapper.Map<FaqViewModel>(faq);
            return View(model);
        }

        // GET: Faqs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Faqs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FaqViewModel model)
        {
            try
            {
                // TODO: Add insert logic here
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var faq = _mapper.Map<Faq>(model);
                var isSuccess = _repo.Create(faq);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong!");
                    return View(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong!");
                return View(model);
            }
        }

        // GET: Faqs/Edit/5
        public ActionResult Edit(int id)
        {
            if (!_repo.isExists(id))
            {
                return NotFound();
            }
            var faq = _repo.FindById(id);
            var model = _mapper.Map<FaqViewModel>(faq);
            return View(model);
        }

        // POST: Faqs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Faq model) 
        {
            try
            {
                // TODO: Add update logic here
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var faq = _mapper.Map<Faq>(model);
                var isSuccess = _repo.Update(faq);
                if(!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong!");
                    return View(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong!");
                return View(model);
            }
        }

        // GET: Faqs/Delete/5
        public ActionResult Delete(int id)
        {
            // TODO: Add delete logic here
            var faq = _repo.FindById(id);
            if (faq == null)
            {
                return NotFound();
            }

            var isSuccess = _repo.Delete(faq);
            if (!isSuccess)
            {
                return BadRequest();
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Faqs/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, FaqViewModel model)
        {
            try
            {
                // TODO: Add delete logic here
                var faq = _repo.FindById(id);
                if (faq == null)
                {
                    return NotFound();
                }

                var isSuccess = _repo.Delete(faq);
                if (!isSuccess)
                {
                    return View(model);
                }


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(model);
            }
        }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using epeacweb.Contracts;
using epeacweb.Data;
using epeacweb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace epeacweb.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly IProjectRepository _repo;
        private readonly IMapper _mapper;

        public ProjectsController(IProjectRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }
        // GET: Projects
        public ActionResult Index()
        {
            var Projects = _repo.FindAll().ToList();
            var model = _mapper.Map<List<Project>, List<ProjectViewModel>>(Projects);
            return View(model);
        }

        // GET: Projects/Details/5
        public ActionResult Details(int id)
        {
            if(!_repo.isExists(id))
            {
                return NotFound();
            }
            var Project = _repo.FindById(id);
            var model = _mapper.Map<ProjectViewModel>(Project);
            return View(model);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProjectViewModel model)
        {
            try
            {
                // TODO: Add insert logic here
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var Project = _mapper.Map<Project>(model);
                var isSuccess = _repo.Create(Project);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong!");
                    return View(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong!");
                return View(model);
            }
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int id)
        {
            if (!_repo.isExists(id))
            {
                return NotFound();
            }
            var Project = _repo.FindById(id);
            var model = _mapper.Map<ProjectViewModel>(Project);
            return View(model);
        }

        // POST: Projects/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Project model) 
        {
            try
            {
                // TODO: Add update logic here
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var Project = _mapper.Map<Project>(model);
                var isSuccess = _repo.Update(Project);
                if(!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong!");
                    return View(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong!");
                return View(model);
            }
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int id)
        {
            // TODO: Add delete logic here
            var Project = _repo.FindById(id);
            if (Project == null)
            {
                return NotFound();
            }

            var isSuccess = _repo.Delete(Project);
            if (!isSuccess)
            {
                return BadRequest();
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Projects/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, ProjectViewModel model)
        {
            try
            {
                // TODO: Add delete logic here
                var Project = _repo.FindById(id);
                if (Project == null)
                {
                    return NotFound();
                }

                var isSuccess = _repo.Delete(Project);
                if (!isSuccess)
                {
                    return View(model);
                }


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(model);
            }
        }
    }
}

Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace epeacweb.Controllers
{
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> roleManager;

        /// 
        /// Injecting Role Manager
        /// 
        /// 
        public RoleController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = roleManager.Roles.ToList();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View(new IdentityRole());
        }

        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            await roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
    }
}

Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using epeacweb.Contracts;
using epeacweb.Data;
using epeacweb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace epeacweb.Controllers
{
    public class TasksController : Controller
    {
        private readonly ITaskRepository _repo;
        private readonly IMapper _mapper;

        public TasksController(ITaskRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }
        // GET: Tasks
        public ActionResult Index()
        {
            var tasks = _repo.FindAll().ToList();
            var model = _mapper.Map<List<Task>, List<TaskViewModel>>(tasks);
            return View(model);
        }

        // GET: Tasks/Details/5
        public ActionResult Details(int id)
        {
            if (!_repo.isExists(id))
            {
                return NotFound();
            }
            var faq = _repo.FindById(id);
            var model = _mapper.Map<TaskViewModel>(faq);
            return View(model);
        }

        // GET: Tasks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tasks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TaskViewModel model)
        {
            try
            {
                // TODO: Add insert logic here
                if(!ModelState.IsValid)
                {
                    return View(model);
                }
                var task = _mapper.Map<Task>(model);
                var isSuccess = _repo.Create(task);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong!");
                    return View(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Tasks/Edit/5
        public ActionResult Edit(int id)
        {
            {
                if (!_repo.isExists(id))
                {
                    return NotFound();
                }
                var faq = _repo.FindById(id);
                var model = _mapper.Map<TaskViewModel>(faq);
                return View(model);
            }
        }

        // POST: Tasks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Faq model)
        {
            try
            {
                // TODO: Add update logic here
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                var task = _mapper.Map<Task>(model);
                var isSuccess = _repo.Update(task);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong!");
                    return View(model);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong!");
                return View(model);
            }
        }

        // GET: Tasks/Delete/5
        public ActionResult Delete(int id)
        {
            // TODO: Add delete logic here
            var task = _repo.FindById(id);
            if (task == null)
            {
                return NotFound();
            }

            var isSuccess = _repo.Delete(task);
            if (!isSuccess)
            {
                return BadRequest();
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Faqs/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, TaskViewModel model)
        {
            try
            {
                // TODO: Add delete logic here
                var task = _repo.FindById(id);
                if (task == null)
                {
                    return NotFound();
                }

                var isSuccess = _repo.Delete(task);
                if (!isSuccess)
                {
                    return View(model);
                }


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(model);
            }
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - epeacweb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">

                    <img src="~/images/navbar_logo.png" height="50" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">User registration</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role administration</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        CRUD
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item text-dark" asp-controller="AcheivementPhrases" asp-action="Index">AcheivementPhrases</a>
                                        <a class="dropdown-item text-dark" asp-controller="Departments" asp-action="Index">Departments</a>
                                        <a class="dropdown-item text-dark" asp-controller="DepartmentManagers" asp-action="Index">DepartmentManagers</a>
                                        <a class="dropdown-item text-dark" asp-controller="Employees" asp-action="Index">Employees</a>
                                        <a class="dropdown-item text-dark" asp-controller="EpeacUsers" asp-action="Index">EpeacUsers</a>
                                        <a class="dropdown-item text-dark" asp-controller="Faqs" asp-action="Index">FAQ</a>
                                        <a class="dropdown-item text-dark" asp-controller="ProjectManagers" asp-action="Index">ProjectManagers</a>
                                        <a class="dropdown-item text-dark" asp-controller="Projects" asp-action="Index">Projects</a>
                                        <a class="dropdown-item text-dark" asp-controller="Tasks" asp-action="Index">Tasks</a>
                                        <a class="dropdown-item text-dark" asp-controller="CommunicationPhrases" asp-action="Index">CommunicationPhrases</a>
                                        <a class="dropdown-item text-dark" asp-controller="CooperationPhrases" asp-action="Index">CooperationPhrases</a>
                                        <a class="dropdown-item text-dark" asp-controller="CreativityPhrases" asp-action="Index">CreativityPhrases</a>
                                        <a class="dropdown-item text-dark" asp-controller="PunctualityPhrases" asp-action="Index">PunctualityPhrases</a>
                                        <a class="dropdown-item text-dark" asp-controller="DrivePhrases" asp-action="Index">DrivePhrases</a>
                                        <a class="dropdown-item text-dark" asp-controller="ContactForms" asp-action="Index">ContactForms</a>
                                        <a class="dropdown-item text-dark" asp-controller="EmployeeProjectAttendances" asp-action="Index">Funker ikke - EmployeeProjectAttendances</a>
                                        <a class="dropdown-item text-dark" asp-controller="ProjectRoles" asp-action="Index">ProjectRoles</a>
                                        <a class="dropdown-item text-dark" asp-controller="Milestones" asp-action="Index">Milestones</a>
                                        <a class="dropdown-item text-dark" asp-controller="EmployeeTaskRatings" asp-action="Index">Funker ikke - EmployeeTaskRatings</a>



                                    </div>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Team 10
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>